version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nusarithm-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs
      - ./migrations:/app/migrations
    restart: unless-stopped
